services:
  - type: web
    name: codelearn
    env: node
    region: ohio
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
